import {
  createSlice,
  createAsyncThunk,
  createEntityAdapter,
  createSelector,
} from "@reduxjs/toolkit";
import { fetchRecentTrips } from "../../services/trips";
import type { TripPublic } from "../../types/trip";
import type { RootState } from "../trip/store";

// maintains trip ids in sorted order
// by last updated date, most recent first
// normalizes trip data
const tripsAdapter = createEntityAdapter<TripPublic>({
  sortComparer: (a, b) =>
    new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(),
});

// fetches the 4 most recent trips for a given userId
export const loadRecentTrips = createAsyncThunk(
  "trips/loadRecent",
  async (userId: number) => {
    return fetchRecentTrips(4, userId);
  },
);

// fetches a trip by its ID
export const loadTripById = createAsyncThunk(
  "trips/loadById",
  async ({ tripId, userId }: { tripId: string; userId: number }) => {
    const { getTripById } = await import("../../services/trips");
    return getTripById(tripId, userId); // Your existing API call
  },
);

// fetches a trip by its ID
export const selectTripDetailById = createAsyncThunk(
  "trips/loadByIdDetail",
  async ({ tripId, userId }: { tripId: string; userId: number }) => {
    const { getTripById } = await import("../../services/trips");
    const trip = await getTripById(tripId, userId);
    return trip;
  },
);

const tripsSlice = createSlice({
  name: "trips",
  initialState: tripsAdapter.getInitialState({
    status: "idle" as "idle" | "loading" | "succeeded" | "failed",
    error: null as string | null,
  }),
  reducers: {},
  extraReducers: (builder) => {
    builder
      //loadRecentTrips
      .addCase(loadRecentTrips.pending, (state) => {
        state.status = "loading";
      })
      .addCase(loadRecentTrips.fulfilled, (state, action) => {
        state.status = "succeeded";
        tripsAdapter.setAll(state, action.payload); // or upsertMany
      })
      .addCase(loadRecentTrips.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.error.message ?? "Unknown error";
      })

      // loadTripById
      .addCase(loadTripById.pending, (state) => {
        state.status = "loading";
      })
      .addCase(loadTripById.fulfilled, (state, action) => {
        state.status = "succeeded";
        tripsAdapter.upsertOne(state, action.payload);
      })
      .addCase(loadTripById.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.error.message ?? "Failed to load trip";
      })

      // selectTripDetailById
      .addCase(selectTripDetailById.pending, (state) => {
        state.status = "loading";
      })
      .addCase(selectTripDetailById.fulfilled, (state, action) => {
        state.status = "succeeded";
        tripsAdapter.upsertOne(state, action.payload);
      })
      .addCase(selectTripDetailById.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.error.message ?? "Failed to load trip";
      });
  },
});

// Base selectors generated by the adapter
const baseSelectors = tripsAdapter.getSelectors(
  (state: RootState) => state.trips,
);

// Export the base selectors
export const selectAllTrips = baseSelectors.selectAll;
export const selectTripById = baseSelectors.selectById;
export const selectTripIds = baseSelectors.selectIds;

// Status selectors
export const selectTripsStatus = (state: RootState) => state.trips.status;
export const selectTripsError = (state: RootState) => state.trips.error;

// Derived selector: get the N most recent trips (already sorted by adapter)
export const selectRecentTrips = createSelector(
  [selectAllTrips, (_state: RootState, limit: number) => limit],
  (trips, limit) => trips.slice(0, limit),
);

// Derived selector: check if a specific trip is in the cache
export const selectHasTrip = createSelector(
  [selectTripIds, (_state: RootState, tripId: number) => tripId],
  (ids, tripId) => ids.includes(tripId),
);

export default tripsSlice.reducer;
